language: node_js
node_js:
  - "6"
os:
- linux
- osx
dist: trusty
sudo: required

before_script:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install rpm; fi
  # - npm install -g electron-forge

script:
 - npm run test

after_script:
 - ./publish.sh
